# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_offer_parameter_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_url_base', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_idfa_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_ip_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_offer_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_appid_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_appid_parameter_value', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_callback_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_success_text', models.CharField(blank=True, max_length=200, null=True)),
                ('callback_success_text', models.CharField(blank=True, max_length=200, null=True)),
                ('check_url_base', models.CharField(blank=True, max_length=200, null=True)),
                ('check_idfa_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('check_success_text', models.CharField(blank=True, max_length=200, null=True)),
                ('callback_server_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_openudid_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_os_version_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_device_name_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('check_openudid_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('check_os_version_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('check_ip_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_http_method', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_sign_parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_sign_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfa', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('callback_url', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_result_text', models.CharField(blank=True, max_length=200, null=True)),
                ('callback_result_text', models.CharField(blank=True, max_length=200, null=True)),
                ('openudid', models.CharField(blank=True, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, max_length=200, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.DateTimeField(auto_now_add=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Channel')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Provider'),
        ),
    ]
