# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_checkidfa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='day',
            new_name='day_time',
        ),
        migrations.AddField(
            model_name='checkidfa',
            name='day_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
